include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - ios/**
    - android/**
  errors:
    missing_required_param: error
    missing_return: error
    invalid_assignment: error

linter:
  rules:
    # 🔥 Code Style
    prefer_single_quotes: true
    always_use_package_imports: true
    sort_constructors_first: true
    sort_pub_dependencies: true

    # 🧠 Readability & Maintainability
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true

    # 🚫 Bad Practices Prevention
    avoid_returning_null_for_void: true
    avoid_types_as_parameter_names: true
    no_logic_in_create_state: true
    avoid_dynamic_calls: true

    # ⚡ Performance
    prefer_const_declarations: true
    avoid_unnecessary_containers: true

    # 🧪 Null Safety & Safety Rules
    always_declare_return_types: true

    # 🏗 Architecture (important for you)
    depend_on_referenced_packages: true
    implementation_imports: true

    # 📦 Naming Conventions
    camel_case_types: true
    file_names: true
    constant_identifier_names: false

    # 🧹 Clean Code
    unnecessary_null_checks: true
    unnecessary_overrides: true
