import 'package:fit_flow/core/firestore/normalization/normalized_firestore_models.dart';

LocalizedText _text(String en, String ar) {
  return LocalizedText(en: en, ar: ar);
}

LocalizedTextList _textList(List<String> en, List<String> ar) {
  return LocalizedTextList(en: en, ar: ar);
}

NormalizedExerciseDocument _exercise({
  required String id,
  required String muscleGroup,
  required String equipment,
  required String difficulty,
  required String category,
  required int defaultSets,
  required String defaultReps,
  required String nameEn,
  required String nameAr,
  required String descriptionEn,
  required String descriptionAr,
  required List<String> instructionsEn,
  required List<String> instructionsAr,
  required List<String> secondaryMuscles,
}) {
  return NormalizedExerciseDocument(
    id: id,
    muscleGroup: muscleGroup,
    equipment: equipment,
    difficulty: difficulty,
    category: category,
    defaultSets: defaultSets,
    defaultReps: defaultReps,
    name: _text(nameEn, nameAr),
    description: _text(descriptionEn, descriptionAr),
    instructions: _textList(instructionsEn, instructionsAr),
    secondaryMuscles: secondaryMuscles,
  );
}

WorkoutTemplateExerciseDocument _slot(String exerciseId, int sets, String reps) {
  return WorkoutTemplateExerciseDocument(
    exerciseId: exerciseId,
    sets: sets,
    reps: reps,
  );
}

WorkoutTemplateDayDocument _day(
  int dayIndex,
  String nameEn,
  String nameAr,
  List<WorkoutTemplateExerciseDocument> exercises,
) {
  return WorkoutTemplateDayDocument(
    dayIndex: dayIndex,
    name: _text(nameEn, nameAr),
    exercises: exercises,
  );
}

NormalizedWorkoutTemplateDocument _template({
  required String id,
  required String goal,
  required int daysPerWeek,
  required String nameEn,
  required String nameAr,
  required String descriptionEn,
  required String descriptionAr,
  required List<WorkoutTemplateDayDocument> days,
}) {
  return NormalizedWorkoutTemplateDocument(
    id: id,
    goal: goal,
    daysPerWeek: daysPerWeek,
    name: _text(nameEn, nameAr),
    description: _text(descriptionEn, descriptionAr),
    days: days,
  );
}

NormalizedLearnDocument _learn({
  required String id,
  required String categoryEn,
  required String categoryAr,
  required String titleEn,
  required String titleAr,
  required String contentEn,
  required String contentAr,
  required String videoUrl,
  required String thumbnailUrl,
}) {
  return NormalizedLearnDocument(
    id: id,
    category: _text(categoryEn, categoryAr),
    title: _text(titleEn, titleAr),
    content: _text(contentEn, contentAr),
    videoUrl: videoUrl,
    thumbnailUrl: thumbnailUrl,
  );
}

final List<NormalizedExerciseDocument> canonicalExercises = [
  _exercise(
    id: 'bench_press',
    muscleGroup: 'chest',
    equipment: 'barbell',
    difficulty: 'intermediate',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '6-10',
    nameEn: 'Bench Press',
    nameAr: 'بنش برس',
    descriptionEn: 'Foundational press for chest, shoulders, and triceps strength.',
    descriptionAr: 'تمرين ضغط اساسي لبناء الصدر والكتف والترايسبس.',
    instructionsEn: [
      'Set your upper back tight and keep your feet planted.',
      'Lower the bar to the mid chest with control.',
      'Press up in a straight line without losing shoulder position.',
    ],
    instructionsAr: [
      'ثبت اعلى الظهر وخلي رجلك ثابتة على الارض.',
      'نزل البار لمنتصف الصدر بتحكم.',
      'اطلع بالبار بخط ثابت بدون ما تفك الكتف.',
    ],
    secondaryMuscles: ['shoulders', 'triceps'],
  ),
  _exercise(
    id: 'incline_dumbbell_press',
    muscleGroup: 'chest',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '8-12',
    nameEn: 'Incline Dumbbell Press',
    nameAr: 'انكلاين دمبل برس',
    descriptionEn: 'Upper chest focused press with independent dumbbell control.',
    descriptionAr: 'تمرين ضغط يركز على الجزء العلوي من الصدر مع تحكم مستقل بكل دمبل.',
    instructionsEn: [
      'Set the bench to a mild incline.',
      'Lower the dumbbells beside the upper chest.',
      'Press up while keeping your wrists stacked over elbows.',
    ],
    instructionsAr: [
      'اضبط البنش على انكلاين خفيف.',
      'نزل الدمبلز بجانب اعلى الصدر.',
      'اطلع بالدمبلز مع ثبات الرسغ فوق الكوع.',
    ],
    secondaryMuscles: ['shoulders', 'triceps'],
  ),
  _exercise(
    id: 'overhead_barbell_press',
    muscleGroup: 'shoulders',
    equipment: 'barbell',
    difficulty: 'intermediate',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '5-8',
    nameEn: 'Overhead Barbell Press',
    nameAr: 'باربل اوفرهيد برس',
    descriptionEn: 'Vertical press that builds shoulder strength and pressing power.',
    descriptionAr: 'تمرين ضغط عمودي يبني قوة الكتف ويطور قوة الدفع.',
    instructionsEn: [
      'Brace your core and squeeze your glutes before the press.',
      'Move your head back slightly to let the bar travel up.',
      'Finish with the bar stacked over your shoulders.',
    ],
    instructionsAr: [
      'شد الكور واضغط الجلوتس قبل ما تبدأ.',
      'ارجع راسك شوي عشان البار يطلع بخط مستقيم.',
      'ثبت البار فوق الكتف في اخر الحركة.',
    ],
    secondaryMuscles: ['triceps', 'core'],
  ),
  _exercise(
    id: 'dumbbell_shoulder_press',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    category: 'compound',
    defaultSets: 3,
    defaultReps: '8-12',
    nameEn: 'Dumbbell Shoulder Press',
    nameAr: 'دمبل شولدر برس',
    descriptionEn: 'Stable seated or standing shoulder press with a natural arm path.',
    descriptionAr: 'تمرين كتف ثابت بالدمبل بمسار مريح وطبيعي للذراع.',
    instructionsEn: [
      'Start with dumbbells at ear level.',
      'Press up while keeping your ribs down.',
      'Lower slowly to maintain shoulder control.',
    ],
    instructionsAr: [
      'ابدأ والدمبل عند مستوى الاذن.',
      'اطلع بالدمبلز مع الحفاظ على القفص الصدري ثابت.',
      'انزل ببطء عشان تحافظ على التحكم.',
    ],
    secondaryMuscles: ['triceps', 'core'],
  ),
  _exercise(
    id: 'arnold_press',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    category: 'compound',
    defaultSets: 3,
    defaultReps: '10-12',
    nameEn: 'Arnold Press',
    nameAr: 'ارنولد برس',
    descriptionEn: 'Rotational dumbbell press that trains the front and side delts.',
    descriptionAr: 'تمرين ضغط بالدمبل مع دوران يشغل الامامي والجانبي من الكتف.',
    instructionsEn: [
      'Start with palms facing you at shoulder height.',
      'Rotate the dumbbells as you press overhead.',
      'Reverse the motion under control on the way down.',
    ],
    instructionsAr: [
      'ابدأ والكف مواجه لك عند مستوى الكتف.',
      'لف الدمبل وانت طالع لفوق.',
      'ارجع بنفس المسار وتحكم وانت نازل.',
    ],
    secondaryMuscles: ['triceps'],
  ),
  _exercise(
    id: 'lateral_raise',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '12-15',
    nameEn: 'Lateral Raise',
    nameAr: 'لاترال رايز',
    descriptionEn: 'Isolation move for building wider side delts.',
    descriptionAr: 'تمرين عزل ممتاز لتكبير الجانب الجانبي من الكتف.',
    instructionsEn: [
      'Keep a slight bend in the elbows.',
      'Raise the dumbbells out to shoulder height.',
      'Lower slowly without swinging your torso.',
    ],
    instructionsAr: [
      'خلي الكوع مثني شوي.',
      'ارفع الدمبلز لحد مستوى الكتف.',
      'انزل ببطء بدون ترمي جسمك.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'tricep_rope_pushdown',
    muscleGroup: 'triceps',
    equipment: 'cable',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '10-15',
    nameEn: 'Tricep Rope Pushdown',
    nameAr: 'ترايسبس روب بوشداون',
    descriptionEn: 'Cable isolation exercise for full triceps contraction.',
    descriptionAr: 'تمرين كابل لعزل الترايسبس وتحقيق انقباض كامل.',
    instructionsEn: [
      'Pin your elbows to your sides.',
      'Push the rope down and spread the ends apart.',
      'Control the return without letting the stack crash.',
    ],
    instructionsAr: [
      'ثبت الكوع جنب جسمك.',
      'ادفع الحبل لتحت وافتح الطرفين.',
      'ارجع ببطء بدون ما ترمي الوزن.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'skull_crusher',
    muscleGroup: 'triceps',
    equipment: 'barbell',
    difficulty: 'intermediate',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '8-12',
    nameEn: 'Skull Crusher',
    nameAr: 'سكال كراشر',
    descriptionEn: 'Lying triceps extension for long head development.',
    descriptionAr: 'تمرين ترايسبس على البنش يستهدف الراس الطويلة بشكل قوي.',
    instructionsEn: [
      'Hold the bar above your shoulders.',
      'Bend at the elbows and lower toward the forehead line.',
      'Extend back up without flaring your elbows hard.',
    ],
    instructionsAr: [
      'ثبت البار فوق الكتف.',
      'اثني الكوع ونزل ناحية الجبهة بتحكم.',
      'ارجع اطلع بدون ما تفتح الكوع زيادة.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'dip',
    muscleGroup: 'chest',
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    category: 'compound',
    defaultSets: 3,
    defaultReps: '8-12',
    nameEn: 'Dip',
    nameAr: 'ديبس',
    descriptionEn: 'Bodyweight press that loads the lower chest and triceps.',
    descriptionAr: 'تمرين وزن جسم قوي للصدر السفلي والترايسبس.',
    instructionsEn: [
      'Support your body with locked elbows at the top.',
      'Lean slightly forward as you lower.',
      'Drive back up without collapsing your shoulders.',
    ],
    instructionsAr: [
      'ثبت جسمك والكوع مقفول في البداية.',
      'امِل شوي لقدام وانت نازل.',
      'اطلع بدون ما الكتف يقع لقدام.',
    ],
    secondaryMuscles: ['triceps', 'shoulders'],
  ),
  _exercise(
    id: 'push_up',
    muscleGroup: 'chest',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    category: 'compound',
    defaultSets: 3,
    defaultReps: '12-20',
    nameEn: 'Push-Up',
    nameAr: 'بوش اب',
    descriptionEn: 'Classic bodyweight press for chest, shoulders, and core control.',
    descriptionAr: 'تمرين وزن جسم اساسي للصدر والكتف مع ثبات ممتاز للكور.',
    instructionsEn: [
      'Keep your body in one straight line.',
      'Lower your chest until it is just above the floor.',
      'Push back up while keeping your core braced.',
    ],
    instructionsAr: [
      'خلي جسمك بخط واحد.',
      'انزل لحد ما صدرك يقرب من الارض.',
      'اطلع مع شد الكور طوال الحركة.',
    ],
    secondaryMuscles: ['triceps', 'core'],
  ),
  _exercise(
    id: 'pull_up',
    muscleGroup: 'back',
    equipment: 'bodyweight',
    difficulty: 'advanced',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '5-8',
    nameEn: 'Pull-Up',
    nameAr: 'بول اب',
    descriptionEn: 'Top-tier vertical pulling exercise for back width and strength.',
    descriptionAr: 'من اقوى تمارين السحب العمودي لعرض الظهر والقوة.',
    instructionsEn: [
      'Start from a dead hang with a tight core.',
      'Pull your chest toward the bar.',
      'Lower fully under control before the next rep.',
    ],
    instructionsAr: [
      'ابدأ من وضع تعليق كامل مع شد الكور.',
      'اسحب صدرك ناحية البار.',
      'انزل للنهاية بتحكم قبل التكرار التالي.',
    ],
    secondaryMuscles: ['biceps', 'shoulders'],
  ),
  _exercise(
    id: 'lat_pulldown',
    muscleGroup: 'back',
    equipment: 'cable',
    difficulty: 'beginner',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '8-12',
    nameEn: 'Lat Pulldown',
    nameAr: 'لات بولداون',
    descriptionEn: 'Machine-based vertical pull for lat development and pull-up carryover.',
    descriptionAr: 'تمرين سحب عمودي على الكابل لتقوية اللاتس وتحسين البول اب.',
    instructionsEn: [
      'Sit tall and lock your thighs under the pad.',
      'Pull the bar toward your upper chest.',
      'Return slowly to a full stretch.',
    ],
    instructionsAr: [
      'اجلس مستقيم وثبت الفخذ تحت الباد.',
      'اسحب البار لاعلى الصدر.',
      'ارجع ببطء لمدى كامل.',
    ],
    secondaryMuscles: ['biceps'],
  ),
  _exercise(
    id: 'barbell_row',
    muscleGroup: 'back',
    equipment: 'barbell',
    difficulty: 'intermediate',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '6-10',
    nameEn: 'Barbell Row',
    nameAr: 'باربل رو',
    descriptionEn: 'Heavy horizontal pull for upper-back thickness.',
    descriptionAr: 'تمرين سحب افقي ثقيل لزيادة سماكة الظهر.',
    instructionsEn: [
      'Hinge at the hips and brace your torso.',
      'Row the bar toward your lower ribs.',
      'Pause briefly and lower without jerking.',
    ],
    instructionsAr: [
      'اعمل هينج من الحوض وثبت الجذع.',
      'اسحب البار ناحية اسفل القفص الصدري.',
      'وقف لحظة وانزل بدون نتر.',
    ],
    secondaryMuscles: ['biceps', 'posterior_chain'],
  ),
  _exercise(
    id: 'seated_cable_row',
    muscleGroup: 'back',
    equipment: 'cable',
    difficulty: 'beginner',
    category: 'compound',
    defaultSets: 3,
    defaultReps: '10-12',
    nameEn: 'Seated Cable Row',
    nameAr: 'سيتد كابل رو',
    descriptionEn: 'Controlled rowing pattern for mid-back and lats.',
    descriptionAr: 'تمرين سحب متحكم للميد باك واللاتس.',
    instructionsEn: [
      'Sit tall and keep your chest up.',
      'Pull the handle to your waist.',
      'Let the shoulder blades protract on the return.',
    ],
    instructionsAr: [
      'اجلس مستقيم وارفع الصدر.',
      'اسحب المقبض لحد الخصر.',
      'اسمح للكتف يطلع لقدام وانت راجع.',
    ],
    secondaryMuscles: ['biceps'],
  ),
  _exercise(
    id: 'face_pull',
    muscleGroup: 'shoulders',
    equipment: 'cable',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '12-20',
    nameEn: 'Face Pull',
    nameAr: 'فيس بول',
    descriptionEn: 'Rear-delt and upper-back staple for shoulder health.',
    descriptionAr: 'تمرين اساسي للكتف الخلفي واعلى الظهر ويحسن صحة الكتف.',
    instructionsEn: [
      'Set the rope around eye level.',
      'Pull toward your face with elbows high.',
      'Finish by rotating your hands back.',
    ],
    instructionsAr: [
      'اضبط الحبل على مستوى العين.',
      'اسحب ناحية وشك والكوع عالي.',
      'انه الحركة بلف بسيط لليد للخلف.',
    ],
    secondaryMuscles: ['back'],
  ),
  _exercise(
    id: 'barbell_curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '8-12',
    nameEn: 'Barbell Curl',
    nameAr: 'باربل كيرل',
    descriptionEn: 'Basic heavy curl variation for overall biceps size.',
    descriptionAr: 'تمرين كيرل ثقيل اساسي لزيادة حجم البايسبس.',
    instructionsEn: [
      'Keep your elbows near your torso.',
      'Curl without leaning back.',
      'Lower with a controlled eccentric.',
    ],
    instructionsAr: [
      'ثبت الكوع جنب جسمك.',
      'اطلع بالبار بدون ما ترجع ظهرك.',
      'انزل ببطء وتحكم.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'hammer_curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '10-12',
    nameEn: 'Hammer Curl',
    nameAr: 'هامر كيرل',
    descriptionEn: 'Neutral-grip curl that emphasizes the brachialis and forearms.',
    descriptionAr: 'كيرل قبضة محايدة يركز على البراكياليس والساعد.',
    instructionsEn: [
      'Keep palms facing each other.',
      'Curl up without swinging.',
      'Pause briefly and lower with control.',
    ],
    instructionsAr: [
      'خلي الكف مواجه لبعض طول الحركة.',
      'اطلع بدون ترمي الجسم.',
      'وقف لحظة وانزل بتحكم.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'dumbbell_bicep_curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '10-15',
    nameEn: 'Dumbbell Curl',
    nameAr: 'دمبل كيرل',
    descriptionEn: 'Simple dumbbell curl for balanced arm development.',
    descriptionAr: 'تمرين كيرل بسيط بالدمبل لتطوير الذراع بشكل متوازن.',
    instructionsEn: [
      'Start from a full stretch at the bottom.',
      'Rotate the palm up as you curl.',
      'Lower fully before the next rep.',
    ],
    instructionsAr: [
      'ابدأ من مدى كامل تحت.',
      'لف الكف لفوق وانت طالع.',
      'ارجع للنهاية قبل التكرار التالي.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'squat',
    muscleGroup: 'quads',
    equipment: 'barbell',
    difficulty: 'intermediate',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '4-8',
    nameEn: 'Squat',
    nameAr: 'سكوات',
    descriptionEn: 'Foundational lower-body lift for quads, glutes, and total-body strength.',
    descriptionAr: 'تمرين اساسي للرجل يبني الكواد والجلوتس ويرفع القوة العامة.',
    instructionsEn: [
      'Brace hard before descending.',
      'Sit down between your hips while keeping the chest stacked.',
      'Drive up through mid foot and finish tall.',
    ],
    instructionsAr: [
      'شد جسمك قوي قبل النزول.',
      'انزل بين الحوض مع ثبات الصدر.',
      'اطلع من منتصف القدم وانه الحركة واقف.',
    ],
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
  ),
  _exercise(
    id: 'leg_press',
    muscleGroup: 'quads',
    equipment: 'machine',
    difficulty: 'beginner',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '10-15',
    nameEn: 'Leg Press',
    nameAr: 'ليج برس',
    descriptionEn: 'Machine press for quad volume with lower balance demand.',
    descriptionAr: 'تمرين ماكينة ممتاز لزيادة حجم الكواد مع حاجة اقل للتوازن.',
    instructionsEn: [
      'Place your feet shoulder width apart on the platform.',
      'Lower until your knees are deeply bent but controlled.',
      'Press without locking out aggressively.',
    ],
    instructionsAr: [
      'حط رجلك بعرض الكتف على المنصة.',
      'انزل لحد ثني قوي ومتحكم للركبة.',
      'ادفع لفوق بدون قفل قوي للمفصل.',
    ],
    secondaryMuscles: ['glutes'],
  ),
  _exercise(
    id: 'romanian_deadlift',
    muscleGroup: 'hamstrings',
    equipment: 'barbell',
    difficulty: 'intermediate',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '6-10',
    nameEn: 'Romanian Deadlift',
    nameAr: 'رومانيان ديد ليفت',
    descriptionEn: 'Hip-hinge staple for hamstrings, glutes, and posterior chain control.',
    descriptionAr: 'تمرين هينج اساسي للهامسترنج والجلوتس وتقوية السلسلة الخلفية.',
    instructionsEn: [
      'Unlock the knees slightly and push your hips back.',
      'Keep the bar close to your thighs and shins.',
      'Stop when hamstring tension peaks, then drive the hips through.',
    ],
    instructionsAr: [
      'اثني الركبة بسيط وادفع الحوض للخلف.',
      'خلي البار قريب من الرجل طول الحركة.',
      'وقف عند اقصى شد للهامسترنج وارجع بالحوض لقدام.',
    ],
    secondaryMuscles: ['glutes', 'posterior_chain'],
  ),
  _exercise(
    id: 'deadlift',
    muscleGroup: 'posterior_chain',
    equipment: 'barbell',
    difficulty: 'advanced',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '3-5',
    nameEn: 'Deadlift',
    nameAr: 'ديد ليفت',
    descriptionEn: 'Foundational compound lift training the entire posterior chain.',
    descriptionAr: 'تمرين مركب اساسي لتقوية السلسلة الخلفية بالكامل.',
    instructionsEn: [
      'Set the bar over the middle of your foot.',
      'Pull slack out of the bar before you lift.',
      'Push the floor away and stand tall with locked hips.',
    ],
    instructionsAr: [
      'حط البار فوق منتصف القدم.',
      'اشد البار قبل ما ترفع فعلا.',
      'ادفع الارض واطلع لحد ما الحوض يقفل بالكامل.',
    ],
    secondaryMuscles: ['glutes', 'hamstrings', 'back'],
  ),
  _exercise(
    id: 'walking_lunge',
    muscleGroup: 'quads',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    category: 'compound',
    defaultSets: 3,
    defaultReps: '10-12/side',
    nameEn: 'Walking Lunge',
    nameAr: 'ووكينج لانج',
    descriptionEn: 'Dynamic unilateral leg exercise for quads, glutes, and balance.',
    descriptionAr: 'تمرين رجل احادي وديناميكي للكواد والجلوتس والتوازن.',
    instructionsEn: [
      'Take a long controlled step forward.',
      'Drop the back knee toward the floor.',
      'Push through the front foot to move into the next rep.',
    ],
    instructionsAr: [
      'خذ خطوة طويلة ومتحكم فيها.',
      'نزل الركبة الخلفية ناحية الارض.',
      'ادفع بالرجل الامامية وادخل على التكرار التالي.',
    ],
    secondaryMuscles: ['glutes', 'hamstrings'],
  ),
  _exercise(
    id: 'leg_extension',
    muscleGroup: 'quads',
    equipment: 'machine',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '12-15',
    nameEn: 'Leg Extension',
    nameAr: 'ليج اكستنشن',
    descriptionEn: 'Quad isolation for extra volume and fatigue without spinal loading.',
    descriptionAr: 'تمرين عزل للكواد لزيادة الحجم بدون تحميل على الظهر.',
    instructionsEn: [
      'Align the machine pivot with your knee joint.',
      'Extend smoothly to the top.',
      'Lower slowly and keep tension on the quads.',
    ],
    instructionsAr: [
      'اضبط محور الماكينة مع مفصل الركبة.',
      'اطلع بسلاسة للنهاية.',
      'انزل ببطء وخلي الشد على الكواد.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'leg_curl',
    muscleGroup: 'hamstrings',
    equipment: 'machine',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '12-15',
    nameEn: 'Leg Curl',
    nameAr: 'ليج كيرل',
    descriptionEn: 'Hamstring isolation to complement hinge patterns.',
    descriptionAr: 'تمرين عزل للهامسترنج يكمل تمارين الهينج.',
    instructionsEn: [
      'Keep your hips pressed into the pad.',
      'Curl through a full range without lifting the hips.',
      'Lower under control and keep tension.',
    ],
    instructionsAr: [
      'ثبت الحوض على الباد.',
      'اثني الرجل لمدى كامل بدون ما الحوض يطلع.',
      'انزل بتحكم وخلي العضلة شغالة.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'calf_raise',
    muscleGroup: 'legs',
    equipment: 'machine',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 4,
    defaultReps: '12-20',
    nameEn: 'Calf Raise',
    nameAr: 'كالف رايز',
    descriptionEn: 'Direct calf work for ankle strength and lower-leg development.',
    descriptionAr: 'تمرين مباشر للسمانة وتقوية اسفل الرجل.',
    instructionsEn: [
      'Drop into a deep stretch at the bottom.',
      'Drive up through the balls of your feet.',
      'Pause at the top before lowering again.',
    ],
    instructionsAr: [
      'انزل لتمدد كامل تحت.',
      'اطلع من مقدمة القدم.',
      'وقف فوق لحظة قبل ما تنزل ثاني.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'hip_thrust',
    muscleGroup: 'glutes',
    equipment: 'barbell',
    difficulty: 'intermediate',
    category: 'compound',
    defaultSets: 4,
    defaultReps: '8-12',
    nameEn: 'Hip Thrust',
    nameAr: 'هيب ثرست',
    descriptionEn: 'Glute-dominant lift for strength, shape, and hip extension power.',
    descriptionAr: 'تمرين قوي للجلوتس لبناء القوة والشكل وتحسين دفع الحوض.',
    instructionsEn: [
      'Set your upper back against the bench edge.',
      'Drive your hips up until your torso is level.',
      'Squeeze the glutes hard at lockout.',
    ],
    instructionsAr: [
      'ثبت اعلى الظهر على حافة البنش.',
      'ارفع الحوض لحد ما الجذع يبقى مستقيم.',
      'اعصر الجلوتس بقوة في النهاية.',
    ],
    secondaryMuscles: ['hamstrings'],
  ),
  _exercise(
    id: 'bulgarian_split_squat',
    muscleGroup: 'quads',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    category: 'compound',
    defaultSets: 3,
    defaultReps: '8-10/side',
    nameEn: 'Bulgarian Split Squat',
    nameAr: 'بلغاريان سبليت سكوات',
    descriptionEn: 'Unilateral squat variation that builds quads, glutes, and stability.',
    descriptionAr: 'نسخة احادية من السكوات تبني الكواد والجلوتس والثبات.',
    instructionsEn: [
      'Place your back foot on a bench behind you.',
      'Lower straight down through the front leg.',
      'Drive back up without bouncing out of the bottom.',
    ],
    instructionsAr: [
      'حط الرجل الخلفية على بنش وراءك.',
      'انزل لفوق وتحت على الرجل الامامية.',
      'اطلع بدون نطة من تحت.',
    ],
    secondaryMuscles: ['glutes', 'hamstrings'],
  ),
  _exercise(
    id: 'plank',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    category: 'mobility',
    defaultSets: 3,
    defaultReps: '45-60s',
    nameEn: 'Plank',
    nameAr: 'بلانك',
    descriptionEn: 'Core stability drill that teaches full-body bracing.',
    descriptionAr: 'تمرين ثبات للكور يعلمك شد الجسم كله بشكل صحيح.',
    instructionsEn: [
      'Keep elbows under shoulders.',
      'Squeeze glutes and brace your abs.',
      'Hold a straight line from head to heels.',
    ],
    instructionsAr: [
      'خلي الكوع تحت الكتف.',
      'شد الجلوتس والكور.',
      'ثبت جسمك بخط واحد من الراس للكعب.',
    ],
    secondaryMuscles: ['shoulders'],
  ),
  _exercise(
    id: 'hanging_leg_raise',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    difficulty: 'advanced',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '10-15',
    nameEn: 'Hanging Leg Raise',
    nameAr: 'هانجينج ليج رايز',
    descriptionEn: 'Advanced lower-ab movement that also builds grip and control.',
    descriptionAr: 'تمرين متقدم للبطن السفلية مع تقوية القبضة والتحكم.',
    instructionsEn: [
      'Hang tall and avoid swinging.',
      'Raise the legs by curling the pelvis up.',
      'Lower under control to a dead hang.',
    ],
    instructionsAr: [
      'اتعلق بثبات بدون مرجحة.',
      'ارفع الرجل مع لف الحوض لفوق.',
      'انزل بتحكم لحد تعليق كامل.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'russian_twist',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    category: 'mobility',
    defaultSets: 3,
    defaultReps: '16-24',
    nameEn: 'Russian Twist',
    nameAr: 'روسيان تويست',
    descriptionEn: 'Rotational core drill for oblique endurance and control.',
    descriptionAr: 'تمرين دوران للكور يقوي الجوانب ويحسن التحكم.',
    instructionsEn: [
      'Lean back slightly with a tight core.',
      'Rotate side to side from the torso, not just the arms.',
      'Keep the movement smooth and controlled.',
    ],
    instructionsAr: [
      'ارجع شوي للخلف مع شد الكور.',
      'لف من الجذع نفسه مش من الذراع فقط.',
      'خلي الحركة ناعمة ومتحكم فيها.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'crunch',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '15-20',
    nameEn: 'Crunch',
    nameAr: 'كرنش',
    descriptionEn: 'Simple abdominal flexion movement for direct core volume.',
    descriptionAr: 'تمرين بطن بسيط ومباشر لزيادة حجم الشغل على الكور.',
    instructionsEn: [
      'Keep your lower back lightly pressed into the floor.',
      'Curl your shoulders up with the abs.',
      'Lower slowly without relaxing completely.',
    ],
    instructionsAr: [
      'ثبت اسفل الظهر على الارض بشكل خفيف.',
      'اطلع بالكتف باستخدام البطن.',
      'انزل ببطء بدون ما تفك الشد كامل.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'cable_crunch',
    muscleGroup: 'core',
    equipment: 'cable',
    difficulty: 'intermediate',
    category: 'isolation',
    defaultSets: 3,
    defaultReps: '12-15',
    nameEn: 'Cable Crunch',
    nameAr: 'كابل كرنش',
    descriptionEn: 'Weighted abdominal flexion for progressive overload on abs.',
    descriptionAr: 'تمرين بطن بالوزن يسمح بتقدم حقيقي في التحميل.',
    instructionsEn: [
      'Kneel far enough from the machine to keep cable tension.',
      'Curl your ribs toward your pelvis.',
      'Return slowly and keep your hips mostly fixed.',
    ],
    instructionsAr: [
      'ابعد عن الماكينة شوي عشان الشد يفضل موجود.',
      'اقفل القفص الصدري ناحية الحوض.',
      'ارجع ببطء وخلي الحوض ثابت اغلب الوقت.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'ab_wheel_rollout',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    difficulty: 'advanced',
    category: 'mobility',
    defaultSets: 3,
    defaultReps: '8-12',
    nameEn: 'Ab Wheel Rollout',
    nameAr: 'اب ويل رول اوت',
    descriptionEn: 'Challenging anti-extension core drill for strong abs and bracing.',
    descriptionAr: 'تمرين متقدم ضد التمدد يقوي البطن ويحسن الثبات.',
    instructionsEn: [
      'Start from your knees with ribs down.',
      'Roll forward only as far as you can control.',
      'Pull back using the abs, not the hips alone.',
    ],
    instructionsAr: [
      'ابدأ من الركبة مع شد القفص الصدري.',
      'تحرك لقدام بقدر ما تقدر تتحكم.',
      'ارجع باستخدام البطن مش الحوض فقط.',
    ],
    secondaryMuscles: ['shoulders'],
  ),
  _exercise(
    id: 'burpee',
    muscleGroup: 'legs',
    equipment: 'bodyweight',
    difficulty: 'advanced',
    category: 'cardio',
    defaultSets: 3,
    defaultReps: '10-15',
    nameEn: 'Burpee',
    nameAr: 'بيربي',
    descriptionEn: 'High-output conditioning move for full-body endurance.',
    descriptionAr: 'تمرين لياقة قوي يرفع النفس ويشغل الجسم كله.',
    instructionsEn: [
      'Drop to the floor under control.',
      'Kick the feet back and return quickly.',
      'Explode up into the jump each rep.',
    ],
    instructionsAr: [
      'انزل للارض بتحكم.',
      'ارجع الرجل للخلف ثم لقدام بسرعة.',
      'اطلع بقفزة قوية في كل تكرار.',
    ],
    secondaryMuscles: ['core', 'shoulders'],
  ),
  _exercise(
    id: 'running',
    muscleGroup: 'legs',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    category: 'cardio',
    defaultSets: 1,
    defaultReps: '20-30 min',
    nameEn: 'Running',
    nameAr: 'جري',
    descriptionEn: 'Steady-state cardio option for conditioning and calorie burn.',
    descriptionAr: 'خيار كارديو ثابت لتحسين اللياقة وحرق سعرات.',
    instructionsEn: [
      'Start at a pace you can sustain.',
      'Keep your stride relaxed and rhythmic.',
      'Breathe through a steady cadence.',
    ],
    instructionsAr: [
      'ابدأ بسرعة تقدر تكمل عليها.',
      'خلي الخطوة مريحة ومنتظمة.',
      'تنفس على ايقاع ثابت.',
    ],
    secondaryMuscles: ['core'],
  ),
  _exercise(
    id: 'cycling',
    muscleGroup: 'legs',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    category: 'cardio',
    defaultSets: 1,
    defaultReps: '20-30 min',
    nameEn: 'Cycling',
    nameAr: 'عجلة',
    descriptionEn: 'Low-impact cardio that improves conditioning and recovery.',
    descriptionAr: 'كارديو قليل الضغط على المفاصل ويحسن اللياقة والتعافي.',
    instructionsEn: [
      'Set a moderate resistance you can maintain.',
      'Keep your cadence smooth.',
      'Stay upright and avoid shrugging your shoulders.',
    ],
    instructionsAr: [
      'اضبط مقاومة متوسطة تقدر تكمل عليها.',
      'حافظ على ايقاع ثابت.',
      'خليك مستقيم وما ترفع كتفك.',
    ],
    secondaryMuscles: [],
  ),
  _exercise(
    id: 'kettlebell_swing',
    muscleGroup: 'posterior_chain',
    equipment: 'kettlebell',
    difficulty: 'intermediate',
    category: 'cardio',
    defaultSets: 3,
    defaultReps: '15-20',
    nameEn: 'Kettlebell Swing',
    nameAr: 'كيتل بيل سوينج',
    descriptionEn: 'Explosive hinge pattern for power, conditioning, and glutes.',
    descriptionAr: 'تمرين هينج انفجاري للقوة واللياقة والجلوتس.',
    instructionsEn: [
      'Hike the kettlebell back between the legs.',
      'Snap the hips to drive it to chest height.',
      'Let the bell fall back naturally and hinge again.',
    ],
    instructionsAr: [
      'اسحب الكيتل بيل للخلف بين الرجل.',
      'ادفع الحوض بقوة عشان توصل لمستوى الصدر.',
      'خلي الوزن يرجع طبيعي وادخل على هينج جديد.',
    ],
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
  ),
];

final List<NormalizedWorkoutTemplateDocument> canonicalWorkoutTemplates = [
  _template(
    id: 'build_muscle_2_days',
    goal: 'buildMuscle',
    daysPerWeek: 2,
    nameEn: 'Full Body Hypertrophy - 2 Days',
    nameAr: 'فول بودي هايبرتروفي - يومين',
    descriptionEn: 'Two efficient full-body sessions that prioritize compound lifts and enough accessory work to drive muscle growth.',
    descriptionAr: 'برنامج يومين فول بودي يركز على التمارين المركبة مع اكسسوارات كافية لبناء العضلات.',
    days: [
      _day(1, 'Full Body A', 'فول بودي أ', [
        _slot('bench_press', 4, '6-10'),
        _slot('barbell_row', 4, '8-10'),
        _slot('squat', 4, '6-8'),
        _slot('lat_pulldown', 3, '10-12'),
        _slot('lateral_raise', 3, '12-15'),
        _slot('tricep_rope_pushdown', 3, '12-15'),
      ]),
      _day(2, 'Full Body B', 'فول بودي ب', [
        _slot('incline_dumbbell_press', 4, '8-12'),
        _slot('pull_up', 3, '5-8'),
        _slot('romanian_deadlift', 4, '6-10'),
        _slot('leg_press', 3, '10-15'),
        _slot('hammer_curl', 3, '10-12'),
        _slot('cable_crunch', 3, '12-15'),
      ]),
    ],
  ),
  _template(
    id: 'build_muscle_3_days',
    goal: 'buildMuscle',
    daysPerWeek: 3,
    nameEn: 'Push Pull Legs - 3 Days',
    nameAr: 'بوش بول ليجز - 3 ايام',
    descriptionEn: 'Classic hypertrophy split with one focused session for each major movement pattern.',
    descriptionAr: 'تقسيمة كلاسيكية لبناء العضلات مع يوم مخصص لكل نمط حركة رئيسي.',
    days: [
      _day(1, 'Push', 'بوش', [
        _slot('bench_press', 4, '6-10'),
        _slot('incline_dumbbell_press', 3, '8-12'),
        _slot('dumbbell_shoulder_press', 3, '8-12'),
        _slot('lateral_raise', 3, '12-15'),
        _slot('tricep_rope_pushdown', 3, '10-15'),
      ]),
      _day(2, 'Pull', 'بول', [
        _slot('pull_up', 3, '5-8'),
        _slot('barbell_row', 4, '6-10'),
        _slot('seated_cable_row', 3, '10-12'),
        _slot('face_pull', 3, '15-20'),
        _slot('barbell_curl', 3, '8-12'),
      ]),
      _day(3, 'Legs', 'ليجز', [
        _slot('squat', 4, '5-8'),
        _slot('romanian_deadlift', 3, '6-10'),
        _slot('leg_press', 3, '10-15'),
        _slot('leg_curl', 3, '12-15'),
        _slot('calf_raise', 4, '12-20'),
      ]),
    ],
  ),
  _template(
    id: 'build_muscle_4_days',
    goal: 'buildMuscle',
    daysPerWeek: 4,
    nameEn: 'Upper Lower Hypertrophy - 4 Days',
    nameAr: 'ابر لوور هايبرتروفي - 4 ايام',
    descriptionEn: 'Balanced upper-lower split for higher weekly volume and better recovery between muscle groups.',
    descriptionAr: 'تقسيمة ابر ولوور متوازنة بحجم اسبوعي اعلى وتعاف افضل بين العضلات.',
    days: [
      _day(1, 'Upper A', 'ابر أ', [
        _slot('bench_press', 4, '6-8'),
        _slot('barbell_row', 4, '8-10'),
        _slot('overhead_barbell_press', 3, '6-8'),
        _slot('lat_pulldown', 3, '10-12'),
        _slot('barbell_curl', 3, '10-12'),
        _slot('tricep_rope_pushdown', 3, '12-15'),
      ]),
      _day(2, 'Lower A', 'لوور أ', [
        _slot('squat', 4, '5-8'),
        _slot('romanian_deadlift', 4, '6-8'),
        _slot('leg_extension', 3, '12-15'),
        _slot('leg_curl', 3, '12-15'),
        _slot('calf_raise', 4, '12-20'),
      ]),
      _day(3, 'Upper B', 'ابر ب', [
        _slot('incline_dumbbell_press', 4, '8-12'),
        _slot('pull_up', 3, '5-8'),
        _slot('arnold_press', 3, '10-12'),
        _slot('seated_cable_row', 3, '10-12'),
        _slot('hammer_curl', 3, '10-12'),
        _slot('skull_crusher', 3, '8-12'),
      ]),
      _day(4, 'Lower B', 'لوور ب', [
        _slot('leg_press', 4, '10-15'),
        _slot('hip_thrust', 4, '8-12'),
        _slot('bulgarian_split_squat', 3, '8-10/side'),
        _slot('leg_curl', 3, '12-15'),
        _slot('calf_raise', 4, '15-20'),
      ]),
    ],
  ),
  _template(
    id: 'build_muscle_5_days',
    goal: 'buildMuscle',
    daysPerWeek: 5,
    nameEn: 'Push Pull Legs Upper Lower - 5 Days',
    nameAr: 'بوش بول ليجز ابر لوور - 5 ايام',
    descriptionEn: 'High-volume hypertrophy plan that trains each muscle group multiple times per week without duplicating exercise metadata.',
    descriptionAr: 'برنامج حجم عالي لبناء العضلات يدرب كل عضلة اكثر من مرة بالاسبوع بدون تكرار بيانات التمارين.',
    days: [
      _day(1, 'Push', 'بوش', [
        _slot('bench_press', 4, '6-8'),
        _slot('incline_dumbbell_press', 4, '8-10'),
        _slot('dumbbell_shoulder_press', 3, '8-12'),
        _slot('lateral_raise', 3, '12-15'),
        _slot('tricep_rope_pushdown', 3, '10-15'),
      ]),
      _day(2, 'Pull', 'بول', [
        _slot('pull_up', 4, '5-8'),
        _slot('barbell_row', 4, '6-8'),
        _slot('seated_cable_row', 3, '10-12'),
        _slot('face_pull', 3, '15-20'),
        _slot('barbell_curl', 3, '8-12'),
      ]),
      _day(3, 'Legs', 'ليجز', [
        _slot('squat', 4, '5-8'),
        _slot('romanian_deadlift', 4, '6-8'),
        _slot('leg_press', 3, '10-12'),
        _slot('leg_curl', 3, '12-15'),
        _slot('calf_raise', 4, '15-20'),
      ]),
      _day(4, 'Upper Volume', 'ابر فوليوم', [
        _slot('incline_dumbbell_press', 4, '8-12'),
        _slot('lat_pulldown', 4, '10-12'),
        _slot('arnold_press', 3, '10-12'),
        _slot('seated_cable_row', 3, '10-12'),
        _slot('dumbbell_bicep_curl', 3, '10-15'),
        _slot('dip', 3, '8-12'),
      ]),
      _day(5, 'Lower Pump', 'لوور بامب', [
        _slot('leg_press', 4, '12-15'),
        _slot('hip_thrust', 4, '10-12'),
        _slot('walking_lunge', 3, '10-12/side'),
        _slot('leg_extension', 3, '12-15'),
        _slot('calf_raise', 4, '15-20'),
        _slot('cable_crunch', 3, '12-15'),
      ]),
    ],
  ),
  _template(
    id: 'get_strong_2_days',
    goal: 'getStrong',
    daysPerWeek: 2,
    nameEn: 'Full Body Strength - 2 Days',
    nameAr: 'فول بودي سترينجث - يومين',
    descriptionEn: 'Two heavy full-body sessions built around the squat, bench, and deadlift for lifters with limited weekly time.',
    descriptionAr: 'برنامج يومين قوة كامل مبني على السكوات والبنش والديد ليفت للمشغولين خلال الاسبوع.',
    days: [
      _day(1, 'Session A', 'سيشن أ', [
        _slot('squat', 5, '3-5'),
        _slot('bench_press', 5, '3-5'),
        _slot('barbell_row', 4, '5-8'),
        _slot('overhead_barbell_press', 3, '5-6'),
        _slot('plank', 3, '45-60s'),
      ]),
      _day(2, 'Session B', 'سيشن ب', [
        _slot('deadlift', 4, '3-5'),
        _slot('squat', 3, '5-6'),
        _slot('pull_up', 4, '5-8'),
        _slot('bench_press', 4, '5-6'),
        _slot('hanging_leg_raise', 3, '10-12'),
      ]),
    ],
  ),
  _template(
    id: 'get_strong_3_days',
    goal: 'getStrong',
    daysPerWeek: 3,
    nameEn: 'Strength Rotation - 3 Days',
    nameAr: 'تقسيمة قوة - 3 ايام',
    descriptionEn: 'Three-day strength rotation balancing heavy barbell work with enough pulling and core to progress consistently.',
    descriptionAr: 'برنامج قوة 3 ايام يوازن بين البار الثقيل وتمارين السحب والكور للتقدم المستمر.',
    days: [
      _day(1, 'Squat Focus', 'سكوات فوكس', [
        _slot('squat', 5, '3-5'),
        _slot('bench_press', 4, '4-6'),
        _slot('barbell_row', 4, '5-8'),
        _slot('plank', 3, '45-60s'),
      ]),
      _day(2, 'Press Focus', 'برس فوكس', [
        _slot('overhead_barbell_press', 5, '3-5'),
        _slot('bench_press', 4, '4-6'),
        _slot('pull_up', 4, '5-8'),
        _slot('dip', 3, '8-10'),
      ]),
      _day(3, 'Deadlift Focus', 'ديد ليفت فوكس', [
        _slot('deadlift', 5, '2-4'),
        _slot('romanian_deadlift', 3, '5-6'),
        _slot('lat_pulldown', 4, '8-10'),
        _slot('hanging_leg_raise', 3, '10-12'),
      ]),
    ],
  ),
  _template(
    id: 'get_strong_4_days',
    goal: 'getStrong',
    daysPerWeek: 4,
    nameEn: 'Upper Lower Strength - 4 Days',
    nameAr: 'ابر لوور سترينجث - 4 ايام',
    descriptionEn: 'Four-day strength split with two lower and two upper sessions for heavier practice and better load management.',
    descriptionAr: 'تقسيمة قوة 4 ايام فيها يومين رجل ويومين ابر عشان ترفع ثقيل مع توزيع افضل للحمل.',
    days: [
      _day(1, 'Lower Strength', 'لوور سترينجث', [
        _slot('squat', 5, '3-5'),
        _slot('romanian_deadlift', 4, '5-6'),
        _slot('leg_press', 3, '8-10'),
        _slot('plank', 3, '45-60s'),
      ]),
      _day(2, 'Upper Strength', 'ابر سترينجث', [
        _slot('bench_press', 5, '3-5'),
        _slot('barbell_row', 4, '5-6'),
        _slot('overhead_barbell_press', 4, '4-6'),
        _slot('pull_up', 3, '5-8'),
      ]),
      _day(3, 'Lower Power', 'لوور باور', [
        _slot('deadlift', 4, '2-4'),
        _slot('squat', 3, '5-6'),
        _slot('hip_thrust', 3, '6-8'),
        _slot('calf_raise', 4, '12-15'),
      ]),
      _day(4, 'Upper Volume', 'ابر فوليوم', [
        _slot('incline_dumbbell_press', 4, '8-10'),
        _slot('lat_pulldown', 4, '8-10'),
        _slot('arnold_press', 3, '8-10'),
        _slot('face_pull', 3, '15-20'),
      ]),
    ],
  ),
  _template(
    id: 'get_strong_5_days',
    goal: 'getStrong',
    daysPerWeek: 5,
    nameEn: 'Powerbuilding Strength - 5 Days',
    nameAr: 'باوربيلدنج سترينجث - 5 ايام',
    descriptionEn: 'Five-day strength-biased split using three competition lifts and two supportive volume sessions.',
    descriptionAr: 'برنامج قوة 5 ايام يجمع بين الرفعات الرئيسية ويومين حجم داعم للتقدم المستمر.',
    days: [
      _day(1, 'Squat Day', 'يوم السكوات', [
        _slot('squat', 5, '3-5'),
        _slot('leg_press', 4, '8-10'),
        _slot('bulgarian_split_squat', 3, '8/side'),
        _slot('calf_raise', 4, '12-20'),
      ]),
      _day(2, 'Bench Day', 'يوم البنش', [
        _slot('bench_press', 5, '3-5'),
        _slot('incline_dumbbell_press', 4, '6-8'),
        _slot('dip', 3, '8-10'),
        _slot('tricep_rope_pushdown', 3, '10-12'),
      ]),
      _day(3, 'Deadlift Day', 'يوم الديد ليفت', [
        _slot('deadlift', 5, '2-4'),
        _slot('romanian_deadlift', 3, '5-6'),
        _slot('barbell_row', 4, '6-8'),
        _slot('lat_pulldown', 3, '8-10'),
      ]),
      _day(4, 'Press Day', 'يوم البرس', [
        _slot('overhead_barbell_press', 5, '3-5'),
        _slot('pull_up', 4, '5-8'),
        _slot('lateral_raise', 4, '12-15'),
        _slot('face_pull', 3, '15-20'),
      ]),
      _day(5, 'Volume Day', 'يوم الفوليوم', [
        _slot('hip_thrust', 4, '8-10'),
        _slot('seated_cable_row', 4, '10-12'),
        _slot('dumbbell_shoulder_press', 3, '8-10'),
        _slot('hammer_curl', 3, '10-12'),
        _slot('cable_crunch', 3, '12-15'),
      ]),
    ],
  ),
  _template(
    id: 'general_fitness_2_days',
    goal: 'generalFitness',
    daysPerWeek: 2,
    nameEn: 'Upper Lower Basics - 2 Days',
    nameAr: 'ابر لوور اساسيات - يومين',
    descriptionEn: 'Simple two-day split mixing strength, movement quality, and moderate conditioning.',
    descriptionAr: 'برنامج يومين بسيط يجمع بين القوة وجودة الحركة ولياقة متوسطة.',
    days: [
      _day(1, 'Upper + Core', 'ابر + كور', [
        _slot('bench_press', 3, '8-10'),
        _slot('lat_pulldown', 3, '10-12'),
        _slot('dumbbell_shoulder_press', 3, '10-12'),
        _slot('seated_cable_row', 3, '10-12'),
        _slot('plank', 3, '45s'),
      ]),
      _day(2, 'Lower + Conditioning', 'لوور + لياقة', [
        _slot('squat', 3, '8-10'),
        _slot('leg_press', 3, '12-15'),
        _slot('hip_thrust', 3, '10-12'),
        _slot('cycling', 1, '20 min'),
        _slot('crunch', 3, '15-20'),
      ]),
    ],
  ),
  _template(
    id: 'general_fitness_3_days',
    goal: 'generalFitness',
    daysPerWeek: 3,
    nameEn: 'Full Body Fitness - 3 Days',
    nameAr: 'فول بودي للياقة - 3 ايام',
    descriptionEn: 'Three full-body sessions focused on sustainable progress, energy, and movement quality.',
    descriptionAr: 'ثلاث جلسات فول بودي تركز على تقدم مستدام وطاقة عالية وجودة حركة افضل.',
    days: [
      _day(1, 'Full Body A', 'فول بودي أ', [
        _slot('bench_press', 3, '8-10'),
        _slot('barbell_row', 3, '8-10'),
        _slot('squat', 3, '8-10'),
        _slot('plank', 3, '45s'),
      ]),
      _day(2, 'Full Body B', 'فول بودي ب', [
        _slot('incline_dumbbell_press', 3, '10-12'),
        _slot('lat_pulldown', 3, '10-12'),
        _slot('romanian_deadlift', 3, '8-10'),
        _slot('russian_twist', 3, '20'),
      ]),
      _day(3, 'Conditioning', 'لياقة', [
        _slot('kettlebell_swing', 3, '15-20'),
        _slot('walking_lunge', 3, '10/side'),
        _slot('burpee', 3, '10-12'),
        _slot('running', 1, '20 min'),
      ]),
    ],
  ),
  _template(
    id: 'general_fitness_4_days',
    goal: 'generalFitness',
    daysPerWeek: 4,
    nameEn: 'Upper Lower Core Cardio - 4 Days',
    nameAr: 'ابر لوور كور كارديو - 4 ايام',
    descriptionEn: 'Balanced four-day plan that covers resistance training, core, and conditioning without excessive fatigue.',
    descriptionAr: 'خطة متوازنة 4 ايام تشمل مقاومة وكور وكارديو بدون ارهاق مبالغ فيه.',
    days: [
      _day(1, 'Upper', 'ابر', [
        _slot('bench_press', 3, '8-10'),
        _slot('lat_pulldown', 3, '10-12'),
        _slot('dumbbell_shoulder_press', 3, '10-12'),
        _slot('barbell_curl', 3, '10-12'),
      ]),
      _day(2, 'Lower', 'لوور', [
        _slot('squat', 3, '8-10'),
        _slot('leg_press', 3, '12-15'),
        _slot('leg_curl', 3, '12-15'),
        _slot('calf_raise', 3, '15-20'),
      ]),
      _day(3, 'Core', 'كور', [
        _slot('plank', 3, '45-60s'),
        _slot('russian_twist', 3, '20'),
        _slot('hanging_leg_raise', 3, '10-12'),
        _slot('ab_wheel_rollout', 3, '8-10'),
      ]),
      _day(4, 'Cardio', 'كارديو', [
        _slot('running', 1, '25 min'),
        _slot('cycling', 1, '15 min'),
        _slot('burpee', 3, '10'),
        _slot('kettlebell_swing', 3, '15'),
      ]),
    ],
  ),
  _template(
    id: 'general_fitness_5_days',
    goal: 'generalFitness',
    daysPerWeek: 5,
    nameEn: 'Upper Lower Core Upper Lower - 5 Days',
    nameAr: 'ابر لوور كور ابر لوور - 5 ايام',
    descriptionEn: 'Five-day fitness split combining moderate strength work, core training, and active conditioning for general health.',
    descriptionAr: 'تقسيمة 5 ايام للياقة تجمع قوة متوسطة وكور وكارديو نشط للصحة العامة.',
    days: [
      _day(1, 'Upper A', 'ابر أ', [
        _slot('bench_press', 3, '8-10'),
        _slot('lat_pulldown', 3, '10-12'),
        _slot('overhead_barbell_press', 3, '8-10'),
        _slot('hammer_curl', 3, '10-12'),
      ]),
      _day(2, 'Lower A', 'لوور أ', [
        _slot('squat', 3, '8-10'),
        _slot('leg_press', 3, '12-15'),
        _slot('romanian_deadlift', 3, '8-10'),
        _slot('calf_raise', 3, '15-20'),
      ]),
      _day(3, 'Core + Cardio', 'كور + كارديو', [
        _slot('plank', 3, '60s'),
        _slot('russian_twist', 3, '20'),
        _slot('hanging_leg_raise', 3, '10-12'),
        _slot('cycling', 1, '20 min'),
      ]),
      _day(4, 'Upper B', 'ابر ب', [
        _slot('incline_dumbbell_press', 3, '10-12'),
        _slot('seated_cable_row', 3, '10-12'),
        _slot('arnold_press', 3, '10-12'),
        _slot('tricep_rope_pushdown', 3, '12-15'),
      ]),
      _day(5, 'Lower B', 'لوور ب', [
        _slot('hip_thrust', 3, '10-12'),
        _slot('walking_lunge', 3, '10/side'),
        _slot('leg_extension', 3, '12-15'),
        _slot('running', 1, '20 min'),
      ]),
    ],
  ),
];

final List<NormalizedLearnDocument> canonicalLearnDocuments = [
  _learn(
    id: 'beginner_gym_guide',
    categoryEn: 'Beginner Fitness',
    categoryAr: 'لياقة للمبتدئين',
    titleEn: 'Beginner Complete Gym Guide: Where to Start',
    titleAr: 'الدليل الكامل للمبتدئين: منين تبدأ',
    contentEn: 'Start with three full-body sessions each week built around squat, bench press, row, hinge, and overhead press patterns. Chase clean reps before heavy weights. Keep your protein high, sleep well, and stay consistent for months rather than looking for a fast transformation.',
    contentAr: 'ابدأ بثلاث حصص فول بودي في الاسبوع مبنية على السكوات والبنش برس والرو والهينج والاوفرهيد برس. ركز على التكنيك النظيف قبل الوزن العالي. حافظ على البروتين والنوم والاستمرارية لعدة شهور بدل ما تدور على نتيجة سريعة.',
    videoUrl: 'https://youtu.be/XIYuxAeKSM0?si=7k58qCacPPBc2-nR',
    thumbnailUrl: 'https://img.youtube.com/vi/XIYuxAeKSM0/hqdefault.jpg',
  ),
  _learn(
    id: 'compound_lifts',
    categoryEn: 'Training',
    categoryAr: 'التدريب',
    titleEn: 'Compound Lifts: Why They Should Be Your Foundation',
    titleAr: 'التمارين المركبة: ليه لازم تكون الاساس',
    contentEn: 'Compound lifts train multiple joints and muscle groups at once, which makes them the highest-return exercises in most programs. Build your training around squat, deadlift, bench press, overhead press, rows, and pull-ups before adding isolation work.',
    contentAr: 'التمارين المركبة تشغل اكثر من مفصل واكثر من عضلة في نفس الوقت، وده يخليها اعلى تمارين من ناحية العائد. ابن برنامجك على السكوات والديد ليفت والبنش برس والاوفرهيد برس والرو والبول اب قبل ما تزود تمارين العزل.',
    videoUrl: 'https://youtu.be/7NzeBcIkKUs?si=NqKuyvAznSMlqwHW',
    thumbnailUrl: 'https://img.youtube.com/vi/7NzeBcIkKUs/hqdefault.jpg',
  ),
  _learn(
    id: 'calorie_deficit',
    categoryEn: 'Nutrition',
    categoryAr: 'التغذية',
    titleEn: 'Calorie Deficit: The Foundation of Fat Loss',
    titleAr: 'عجز السعرات: اساس خسارة الدهون',
    contentEn: 'Fat loss needs a calorie deficit, but the smart play is a moderate deficit you can keep for months. Prioritize protein, high-volume foods, and resistance training so the weight you lose comes mostly from fat rather than muscle.',
    contentAr: 'خسارة الدهون تحتاج عجز سعرات، لكن الافضل يكون عجز متوسط تقدر تكمل عليه شهور. ركز على البروتين والاطعمة المشبعة وتمرين المقاومة عشان النزول يكون من الدهون اكثر من العضلات.',
    videoUrl: 'https://youtu.be/ZGTMUwEDBu4?si=deQoxM2yijtzkAAh',
    thumbnailUrl: 'https://img.youtube.com/vi/ZGTMUwEDBu4/hqdefault.jpg',
  ),
  _learn(
    id: 'body_recomposition',
    categoryEn: 'Fat Loss',
    categoryAr: 'خسارة الدهون',
    titleEn: 'Body Recomposition: Build Muscle and Lose Fat at the Same Time',
    titleAr: 'اعادة تكوين الجسم: تبني عضل وتخس دهون في نفس الوقت',
    contentEn: 'Recomp works best for beginners, returners, and people carrying more body fat. Stay near maintenance calories, keep protein high, and train hard on compound lifts. Progress is slower than a dedicated bulk or cut, but it can be very effective when your compliance is high.',
    contentAr: 'اعادة التكوين تنجح اكثر مع المبتدئين والعائدين للتمرين والاشخاص اللي عندهم نسبة دهون اعلى. خلي السعرات قريبة من الصيانة، وارفع البروتين، وتمرن بقوة على التمارين المركبة. التقدم ابطأ من تضخيم او تنشيف صريح، لكنه ممتاز لو التزامك عالي.',
    videoUrl: 'https://youtu.be/yWnacRo2VbA?si=wfJNTWbzU9X8Gioj',
    thumbnailUrl: 'https://img.youtube.com/vi/yWnacRo2VbA/hqdefault.jpg',
  ),
  _learn(
    id: 'protein_intake',
    categoryEn: 'Nutrition',
    categoryAr: 'التغذية',
    titleEn: 'How Much Protein Do You Actually Need?',
    titleAr: 'قد ايه بروتين انت فعلا محتاج؟',
    contentEn: 'A practical target for lifters is 1.6 to 2.2 grams of protein per kilogram of bodyweight daily. Split that intake across three to five meals and prioritize real food first, then use shakes only as a convenient top-up.',
    contentAr: 'هدف عملي لمعظم المتدربين هو 1.6 الى 2.2 جرام بروتين لكل كيلو من وزن الجسم يوميا. قسم الكمية على 3 الى 5 وجبات وخلي الاكل الحقيقي هو الاساس، وبعدها استخدم الشيك فقط كحل مريح.',
    videoUrl: 'https://youtu.be/t_UQz2pTpQc?si=wtSnodPXiKfzgHjf',
    thumbnailUrl: 'https://img.youtube.com/vi/t_UQz2pTpQc/hqdefault.jpg',
  ),
  _learn(
    id: 'sleep_and_recovery',
    categoryEn: 'Recovery',
    categoryAr: 'التعافي',
    titleEn: 'Sleep and Recovery: Why Rest Is Part of the Program',
    titleAr: 'النوم والتعافي: ليه الراحة جزء من البرنامج؟',
    contentEn: 'Muscle growth and performance adaptation happen when you recover, not only when you train. Aim for seven to nine hours of sleep, keep your training volume recoverable, and treat rest days as part of the plan rather than a sign you are doing less.',
    contentAr: 'نمو العضلات والتطور في الاداء يحصل وقت التعافي مش وقت التمرين فقط. استهدف 7 الى 9 ساعات نوم، وخلي حجم التمرين مناسب لقدرتك على التعافي، واعتبر يوم الراحة جزء من البرنامج مش تقصير.',
    videoUrl: 'https://youtu.be/pUZvynhxYb4?si=VtsGfIp5hUB_2LeG',
    thumbnailUrl: 'https://img.youtube.com/vi/pUZvynhxYb4/hqdefault.jpg',
  ),
  _learn(
    id: 'supplements_guide',
    categoryEn: 'Supplements',
    categoryAr: 'المكملات',
    titleEn: 'Supplements Guide: What Is Actually Worth It?',
    titleAr: 'دليل المكملات: ايه اللي يستاهل فعلا؟',
    contentEn: 'Most supplements are optional, and many are over-marketed. Focus on food, sleep, and training first. If the basics are already solid, creatine monohydrate, whey protein, and caffeine are the most practical additions for most gym users.',
    contentAr: 'معظم المكملات اختيارية وكثير منها متسوق له زيادة. ركز اولا على الاكل والنوم والتمرين. لو الاساس مضبوط، يبقى الكرياتين والمصل والكافيين هم اكثر الخيارات العملية لمعظم المتدربين.',
    videoUrl: 'https://youtu.be/gexpGeSvAxk?si=poBidEIgP3EYv7z5',
    thumbnailUrl: 'https://img.youtube.com/vi/gexpGeSvAxk/hqdefault.jpg',
  ),
  _learn(
    id: 'fat_loss_fundamentals',
    categoryEn: 'Fat Loss',
    categoryAr: 'خسارة الدهون',
    titleEn: 'Fat Loss Fundamentals: The Only Things That Matter',
    titleAr: 'اساسيات خسارة الدهون: الحاجات الوحيدة اللي تفرق',
    contentEn: 'A sustainable calorie deficit, high protein intake, resistance training, and daily movement are the real levers for fat loss. Aggressive restriction usually backfires because recovery, adherence, and training quality all drop at the same time.',
    contentAr: 'عجز سعرات مستدام، بروتين عالي، تمرين مقاومة، وحركة يومية هم العوامل الحقيقية لخسارة الدهون. الحرمان العنيف غالبا يرتد عليك لان التعافي والالتزام وجودة التمرين ينزلوا كلهم مع بعض.',
    videoUrl: 'https://youtu.be/SRMhrd2--H0?si=2BWTnMlPM137i5Z9',
    thumbnailUrl: 'https://img.youtube.com/vi/SRMhrd2--H0/hqdefault.jpg',
  ),
];

Map<String, dynamic> buildExercisesSeedJson() {
  return {
    for (final exercise in canonicalExercises) exercise.id: exercise.toJson(),
  };
}

Map<String, dynamic> buildWorkoutTemplatesSeedJson() {
  return {
    for (final template in canonicalWorkoutTemplates)
      template.id: template.toJson(),
  };
}

Map<String, dynamic> buildLearnSeedJson() {
  return {
    for (final learn in canonicalLearnDocuments) learn.id: learn.toJson(),
  };
}